name: apideploy

on: 
  push:
    #branches:
    #  - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  output:
    name: writeoutput
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Write output
        shell: pwsh
        run: |
          write-output 'test output line'