# This is a basic workflow to help you get started with Actions

name: Dev-Build-Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
    
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Application
    # The type of runner that the job will run on
    runs-on: windows-2019    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
            node-version: 14.15.0
            
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
     
      - name: Package SFApplication
        run: ./build_deploy/Package.ps1
      
        
      - uses: actions/upload-artifact@master
        with:
          name: SF_Artifacts
          path: .\artifacts
          retention-days: 1
  deploy:
    name: Deploy Application
    runs-on: windows-2019
    needs: build
    steps:
      - name: Setup Artifacts folder
        run: New-Item .\artifacts -ItemType Directory
        
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: SF_Artifacts
          path: .\artifacts
      
      - name: Unzip artifacts
        run: | 
          New-Item .\pkg -ItemType Directory
          Expand-Archive -Path .\artifacts\SF_Artifacts.Zip -DestinationPath .\pkg
      
      - name: Validate Artifacts
        run: ls .\pkg R
          
      #- name: Deploy ServiceFabric Application
      #  run: ./deploy/build_deploy.ps1
        
